"""empty message

Revision ID: 132437a11347
Revises: 814d8bb62fc0
Create Date: 2024-10-29 13:50:04.853446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132437a11347'
down_revision = '814d8bb62fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'city')
    # ### end Alembic commands ###
