"""empty message

Revision ID: e693692c254a
Revises: 132437a11347
Create Date: 2024-10-29 17:40:18.553720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e693692c254a'
down_revision = '132437a11347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'email')
    # ### end Alembic commands ###
